<?php
/**
 */

namespace execut\robotsTxt;


class Bootstrap extends \execut\yii\Bootstrap
{
    public function getDefaultDepends()
    {
        return [
            'modules' => [
                'robotsTxt' => [
                    'class' => Module::class,
                    'cacheExpire' => YII_ENV === 'dev' ? 1 : 0,
                    'components'    => [
                        'generator' => [
                            'class' => \execut\robotsTxt\Generator::class,
                            'sitemap' => [
                                '/sitemap.xml'
                            ],
                            'userAgent' => [
                                '*' => [
                                    'Allow' => [
                                        '/',
                                    ],
                                ],
                            ]
                        ]
                    ],
                ],
            ],
        ];
    }

    public function bootstrap($app)
    {
        parent::bootstrap($app); // TODO: Change the autogenerated stub
        $app->urlManager->addRules([
            ['pattern' => 'robots', 'route' => 'robotsTxt/web/index', 'suffix' => '.txt'],
        ]);
    }
}